In [1]:
from sklearn.datasets import load_iris

In [2]:
iris = load_iris()
iris_data = iris.data
iris_label = iris.target

In [3]:
import pandas as pd
iris_df = pd.DataFrame(data= iris_data, columns = iris.feature_names)
iris_df['label'] = iris_label
iris_df.head(3)

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),label
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0

In [4]:
keys = iris.keys()
print(keys)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [5]:
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

### 교차검증 ###

In [6]:
from sklearn.model_selection import KFold
import numpy as np

dt_clf = DecisionTreeClassifier()
kfold = KFold(n_splits=5)
cv_accuracy=[]

In [7]:
# KFold의 경우 numpy 에서 실행됌, DataFrame으로 진행시 Error
n_iter = 0
feature = iris.data
label = iris.target
for train_index, test_index in kfold.split(feature):
    # KFold 객체에 split() 호출 시 Fold 별 Index를 List 형태로 반환
    X_train, X_test = feature[train_index], feature[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    n_iter +=1
    
    accuracy = np.round(accuracy_score(y_test,pred),4)
    train_size = X_train.shape[0]
    test_size = X_test.shape[0]
    print('n_iter : {0}. accuracy : {1:.4f}, train : {2}, test : {3}'\
          .format(n_iter,accuracy,train_size,test_size))
    print('n_iter : {0}, test : {1}'.format(n_iter,test_index))
    
    cv_accuracy.append(accuracy)
print('Mean of accuray_score : {0:.4f}'.format(np.mean(cv_accuracy)))

n_iter : 1. accuracy : 1.0000, train : 120, test : 30
n_iter : 1, test : [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
n_iter : 2. accuracy : 1.0000, train : 120, test : 30
n_iter : 2, test : [30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53
 54 55 56 57 58 59]
n_iter : 3. accuracy : 0.8667, train : 120, test : 30
n_iter : 3, test : [60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83
 84 85 86 87 88 89]
n_iter : 4. accuracy : 0.9333, train : 120, test : 30
n_iter : 4, test : [ 90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119]
n_iter : 5. accuracy : 0.7333, train : 120, test : 30
n_iter : 5, test : [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
 138 139 140 141 142 143 144 145 146 147 148 149]
Mean of accuray_score : 0.9067

In [8]:
from sklearn.model_selection import StratifiedKFold
from sklearn.metrics import accuracy_score
skfold = StratifiedKFold(n_splits=5)

dt_clf = DecisionTreeClassifier()

n_iter = 0
cv_accuracy = []
for train_index, test_index in skfold.split(feature,label):
    # KFold의 split과 달리 label 까지 넣어줘야함
    X_train, X_test = feature[train_index], feature[test_index]
    y_train, y_test = label[train_index], label[test_index]
    
    dt_clf.fit(X_train,y_train)
    pred = dt_clf.predict(X_test)
    
    # accuracy_score를 다시 호출해주지 않아서 오류 발생 -> 해당 Cell 내 re-import하여 해결
    accuracy = np.round(accuracy_score(y_test,pred),4)
    cv_accuracy.append(accuracy)
    n_iter +=1
    
    print('n_iter : {0}, accuracy_score : {1:.4f}'.format(n_iter,accuracy))
    print('test : ', test_index)

print('mean of accuracy score : {0:4f}'.format(np.mean(cv_accuracy)))

n_iter : 1, accuracy_score : 0.9667
test :  [  0   1   2   3   4   5   6   7   8   9  50  51  52  53  54  55  56  57
  58  59 100 101 102 103 104 105 106 107 108 109]
n_iter : 2, accuracy_score : 0.9667
test :  [ 10  11  12  13  14  15  16  17  18  19  60  61  62  63  64  65  66  67
  68  69 110 111 112 113 114 115 116 117 118 119]
n_iter : 3, accuracy_score : 0.9000
test :  [ 20  21  22  23  24  25  26  27  28  29  70  71  72  73  74  75  76  77
  78  79 120 121 122 123 124 125 126 127 128 129]
n_iter : 4, accuracy_score : 1.0000
test :  [ 30  31  32  33  34  35  36  37  38  39  80  81  82  83  84  85  86  87
  88  89 130 131 132 133 134 135 136 137 138 139]
n_iter : 5, accuracy_score : 1.0000
test :  [ 40  41  42  43  44  45  46  47  48  49  90  91  92  93  94  95  96  97
  98  99 140 141 142 143 144 145 146 147 148 149]
mean of accuracy score : 0.966680

### cross_val_score

In [9]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score

In [10]:
dt_clf = DecisionTreeClassifier()
scores = cross_val_score(dt_clf, feature, label, scoring='accuracy', cv=3)
print(np.round(scores,4))
print(np.round(np.mean(scores),4))

[0.98 0.94 0.98]
0.9667

### GridSearchCV

In [32]:
from sklearn.datasets import load_iris
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV, train_test_split
from sklearn.metrics import accuracy_score

# 데이터를 로딩하고 학습데이타와 테스트 데이터 분리
iris = load_iris()
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, 
                                                    test_size=0.2, random_state=121)
dtree = DecisionTreeClassifier()

### parameter 들을 dictionary 형태로 설정
parameters = {'max_depth':[1, 2, 3], 'min_samples_split':[2,3]}

In [33]:
import pandas as pd

# param_grid의 하이퍼 파라미터들을 3개의 train, test set fold 로 나누어서 테스트 수행 설정.  
### refit=True 가 default 임. True이면 가장 좋은 파라미터 설정으로 재 학습 시킴.  
grid_dtree = GridSearchCV(dtree, param_grid=parameters, cv=3, refit=True, 
                          return_train_score=True)

# 붓꽃 Train 데이터로 param_grid의 하이퍼 파라미터들을 순차적으로 학습/평가 .
grid_dtree.fit(X_train, y_train)

# GridSearchCV 결과는 cv_results_ 라는 딕셔너리로 저장됨. 이를 DataFrame으로 변환
scores_df = pd.DataFrame(grid_dtree.cv_results_)
scores_df[['params', 'mean_test_score', 'rank_test_score', 
           'split0_test_score', 'split1_test_score', 'split2_test_score']]

,params,mean_test_score,rank_test_score,split0_test_score,split1_test_score,split2_test_score
0,"{'max_depth': 1, 'min_samples_split': 2}",0.700000,5,0.700,0.7,0.70
1,"{'max_depth': 1, 'min_samples_split': 3}",0.700000,5,0.700,0.7,0.70
2,"{'max_depth': 2, 'min_samples_split': 2}",0.958333,3,0.925,1.0,0.95
3,"{'max_depth': 2, 'min_samples_split': 3}",0.958333,3,0.925,1.0,0.95
4,"{'max_depth': 3, 'min_samples_split': 2}",0.975000,1,0.975,1.0,0.95
5,"{'max_depth': 3, 'min_samples_split': 3}",0.975000,1,0.975,1.0,0.95

In [36]:
scores_df

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_min_samples_split,params,split0_test_score,split1_test_score,split2_test_score,mean_test_score,std_test_score,rank_test_score,split0_train_score,split1_train_score,split2_train_score,mean_train_score,std_train_score
0,0.001333,0.000472,0.000000,0.000000,1,2,"{'max_depth': 1, 'min_samples_split': 2}",0.700,0.7,0.70,0.700000,1.110223e-16,5,0.7000,0.7000,0.7000,0.700000,1.110223e-16
1,0.000667,0.000471,0.000000,0.000000,1,3,"{'max_depth': 1, 'min_samples_split': 3}",0.700,0.7,0.70,0.700000,1.110223e-16,5,0.7000,0.7000,0.7000,0.700000,1.110223e-16
2,0.000333,0.000471,0.000667,0.000471,2,2,"{'max_depth': 2, 'min_samples_split': 2}",0.925,1.0,0.95,0.958333,3.118048e-02,3,0.9750,0.9375,0.9625,0.958333,1.559024e-02
3,0.000333,0.000471,0.000334,0.000472,2,3,"{'max_depth': 2, 'min_samples_split': 3}",0.925,1.0,0.95,0.958333,3.118048e-02,3,0.9750,0.9375,0.9625,0.958333,1.559024e-02
4,0.000334,0.000472,0.000333,0.000471,3,2,"{'max_depth': 3, 'min_samples_split': 2}",0.975,1.0,0.95,0.975000,2.041241e-02,1,0.9875,0.9625,0.9875,0.979167,1.178511e-02
5,0.000667,0.000472,0.000000,0.000000,3,3,"{'max_depth': 3, 'min_samples_split': 3}",0.975,1.0,0.95,0.975000,2.041241e-02,1,0.9875,0.9625,0.9875,0.979167,1.178511e-02

In [39]:
print(grid_dtree.best_params_)
print('{0:.4f}'.format(grid_dtree.best_score_))

{'max_depth': 3, 'min_samples_split': 2}
0.9750

In [42]:
dt_clf_best = grid_dtree.best_estimator_
pred = dt_clf_best.predict(X_test)
print(np.round(accuracy_score(y_test,pred),4))

0.9667